# see https://docs.silverstripe.org/en/developer_guides/configuration/configuration/

Atwx\Sck\Elements\GalleryElement:
  extensions:
    - PurpleSpider\BasicGalleryExtension\PhotoGalleryExtension

Silverstripe\SiteConfig\SiteConfig:
  extensions:
    - Atwx\Sck\Extensions\CustomSiteConfig

SilverStripe\LinkField\Models\Link:
  extensions:
    - Atwx\Sck\Extensions\LinkExtension

Atwx\Sck\Elements\SliderElement:
  extensions:
    - PurpleSpider\BasicGalleryExtension\PhotoGalleryExtension
  gallery-title: Bilder
  gallery-cms-tab: Main
  content-cms-tab: Top Content

PurpleSpider\BasicGalleryExtension\PhotoGalleryImage:
  extensions:
    - Atwx\Sck\Extensions\PhotoGalleryExtension

SilverStripe\View\SSViewer:
  themes:
    - '$default'
    - '$public'
    - 'depot'
    - 'silverstripe-elemental-suite-foundation-6'

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Atwx\Sck\Extensions\PageExtension

SilverStripe\Assets\File:
  allowed_extensions:
    - svg
  app_categories:
    image:
      - svg
    image/supported:
      - svg
  class_for_file_extension:
    svg: SilverStripe\Assets\Image
